#testing on ubuntu
name: build

on:
  push:
    branches:
      - 'master'
      - '*release*'
  pull_request:
    branches:
      - 'master'

jobs:
  spark24_x86:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    name: Build and Test on Apache Spark 2.4.x

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
          architecture: x64
      - name: Install Python packages (Python 3.7)
        run: |
          python -m pip install --upgrade pip
          pip install pyspark==2.4.4 numpy
      - name: Build Spark NLP on Apache Spark 2.4.x
        run: |
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
          echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
          sudo apt-get update
          sudo apt-get install sbt
          sbt clean
          sbt compile
          sbt -mem 4096 -Dis_spark24=true assemblyAndCopy
      #- name: Test Spark NLP in Scala - Apache Spark 2.4.x
      #  run: |
      #    sbt -mem 4096 -Dis_spark24=true test
      - name: Test Spark NLP in Python - Apache Spark 2.4.x
        run: |
          cd python
          python3.7 -m run-tests
          

  spark_armv7_job:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-18.04
    name: Build and Test on Apache Spark 2.4.x for arm64
    # The host should always be Linux
    
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu18.04

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
          architecture: armv7

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
            
      - name: Install Python packages (Python 3.7)
        run: |
          python -m pip install --upgrade pip
          pip install pyspark==2.4.4 numpy
      - name: Build Spark NLP on Apache Spark 2.4.x
        run: |
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
          echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
          sudo apt-get update
          sudo apt-get install sbt
          sbt clean
          sbt compile
          sbt -mem 4096 -Dis_spark24=true assemblyAndCopy
      - name: Test Spark NLP in Scala - Apache Spark 2.4.x
        run: |
          sbt -mem 4096 -Dis_spark24=true test
      - name: Test Spark NLP in Python - Apache Spark 2.4.x
        run: |
          cd python
          python3.7 -m run-tests
