#testing on ubuntu
name: build

on:
  push:
    branches:
      - 'master'
      - '*release*'
  pull_request:
    branches:
      - 'master'

jobs:

  spark_armv7_job:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    name: Build and Test on Apache Spark 2.4.x for arm64
    strategy:
      matrix:
        os: [ubuntu-18.04]
        pyver: [cp37-cp37m]
    runs-on: ${{ matrix.os }}
    env:
      py: /opt/python/${{ matrix.pyver }}/bin/python
      img: quay.io/pypa/manylinux2014_aarch64
      python-version: ${{ matrix.pyver }}    
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      #- name: Set up JDK 8
      #  uses: actions/setup-java@v1
      #  with:
      #    java-version: 1.8
      #- name: Install Python 3.7
      #  uses: actions/setup-python@v2
      #  with:
      #    python-version: 3.7.7
      #    architecture: arm64         
      - name: Install tools
        run: |
          docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
            ${{ env.img }} ${{ env.py }} -m pip install -U  pip build
      - name: Install and Run tests
        run: |
          docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
            ${{ env.img }} \
            bash -exc '${{ env.py }} -m pip install virtualenv && ${{ env.py }} -m venv .env && \
            source .env/bin/activate && \
            python -m pip install --upgrade pip && \
            yum install -y wget curl && \
            uname -m && \
            yum -y update && \
            yum install -y java-1.8.0-openjdk && \
            whereis java && \
            whereis javac && \
            java -version && \
            export JAVA_HOME=/usr/lib/java && \
            echo $JAVA_HOME && \
            python --version && \
            
            pwd && \
            ls && \
            python3.7 -m pip install --upgrade pip && \
            python3.7 -m pip install pyspark numpy && \
            
            curl https://bintray.com/sbt/rpm/rpm | tee /etc/yum.repos.d/bintray-sbt-rpm.repo && \
            yum install -y sbt && \
            sbt clean && \
            sbt compile && \
            sbt -mem 4096 assemblyAndCopy
            sbt -mem 4096 test
            sbt -mem 4096 -Dis_spark23=true assemblyAndCopy
            sbt -mem 4096 -Dis_spark23=true test
            
            pwd && \
            ls && \
            python --version && \
            java -version && \
            cd python && \
            python3.7 -m run-tests && \
            deactivate'

   
